# Generated by Django 5.0 on 2023-12-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_users_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='UserProfile',
        ),
    ]
