# Generated by Django 5.0 on 2023-12-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_rename_messages_message_rename_users_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
